create type public.charge_concept_category as enum ('regular_dues','extraordinary_dues','service','penalty','adjustment','opening_balance','other');
create type public.charge_batch_distribution as enum ('fixed_per_unit','custom_per_unit');
create type public.charge_batch_status as enum ('draft','posted','reversed');
create type public.receivable_item_type as enum ('charge','opening_balance','adjustment');
create type public.receivable_lifecycle_status as enum ('active','reversed');
create type public.ledger_entry_type as enum ('charge','opening_debit','opening_credit','adjustment_debit','adjustment_credit','reversal');
create type public.ledger_direction as enum ('debit','credit');

alter table public.units
  add constraint units_id_condominium_unique unique(id,condominium_id);

create table public.charge_concepts (
 id uuid primary key default gen_random_uuid(), condominium_id uuid not null references public.condominiums(id) on delete cascade,
 code text not null, name text not null, description text, category public.charge_concept_category not null,
 default_currency_code text check(default_currency_code ~ '^[A-Z]{3}$'), default_amount numeric(18,2) check(default_amount > 0), is_active boolean not null default true,
 created_by uuid not null references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
 unique(condominium_id,code), unique(id,condominium_id)
);
create table public.charge_batches (
 id uuid primary key default gen_random_uuid(), condominium_id uuid not null references public.condominiums(id), concept_id uuid not null,
 name text not null, period text check(period is null or period ~ '^\d{4}-\d{2}$'), issue_date date not null, due_date date not null check(due_date >= issue_date),
 currency_code text not null check(currency_code ~ '^[A-Z]{3}$'), distribution_method public.charge_batch_distribution not null,
 status public.charge_batch_status not null default 'draft', idempotency_key text not null, result jsonb,
 posted_at timestamptz, posted_by uuid references auth.users(id), created_by uuid not null references auth.users(id), created_at timestamptz not null default now(),
 unique(condominium_id,idempotency_key), unique(id,condominium_id), foreign key(concept_id,condominium_id) references public.charge_concepts(id,condominium_id)
);
create table public.receivable_items (
 id uuid primary key default gen_random_uuid(), condominium_id uuid not null references public.condominiums(id), unit_id uuid not null, concept_id uuid, charge_batch_id uuid,
 item_type public.receivable_item_type not null, description text not null, reference text, issue_date date not null, due_date date,
 currency_code text not null check(currency_code ~ '^[A-Z]{3}$'), original_amount numeric(18,2) not null check(original_amount > 0), lifecycle_status public.receivable_lifecycle_status not null default 'active',
 created_by uuid not null references auth.users(id), created_at timestamptz not null default now(), reversed_at timestamptz, reversed_by uuid references auth.users(id), reversal_reason text,
 unique(id,condominium_id,unit_id,currency_code), foreign key(unit_id,condominium_id) references public.units(id,condominium_id),
 foreign key(concept_id,condominium_id) references public.charge_concepts(id,condominium_id), foreign key(charge_batch_id,condominium_id) references public.charge_batches(id,condominium_id)
);
create table public.receivable_ledger_entries (
 id uuid primary key default gen_random_uuid(), condominium_id uuid not null references public.condominiums(id), unit_id uuid not null, receivable_item_id uuid,
 entry_type public.ledger_entry_type not null, direction public.ledger_direction not null, amount numeric(18,2) not null check(amount > 0), currency_code text not null check(currency_code ~ '^[A-Z]{3}$'),
 effective_date date not null, description text not null, reversal_of_entry_id uuid unique references public.receivable_ledger_entries(id), source_id uuid,
 created_by uuid not null references auth.users(id), created_at timestamptz not null default now(),
 foreign key(unit_id,condominium_id) references public.units(id,condominium_id),
 foreign key(receivable_item_id,condominium_id,unit_id,currency_code) references public.receivable_items(id,condominium_id,unit_id,currency_code)
);
create table public.opening_balance_imports (
 id uuid primary key default gen_random_uuid(), condominium_id uuid not null references public.condominiums(id), idempotency_key text not null, filename text,
 currency_codes text[] not null, effective_date_min date not null, effective_date_max date not null, result jsonb not null,
 created_by uuid not null references auth.users(id), created_at timestamptz not null default now(), unique(condominium_id,idempotency_key)
);

create function public.can_manage_receivables(target uuid) returns boolean language sql stable security definer set search_path=public set row_security=off as $$ select public.is_organization_owner_for_condominium(target) or exists(select 1 from public.condominium_memberships where condominium_id=target and user_id=auth.uid() and role in ('condominium_admin','accountant')) $$;
create function public.can_read_receivables(target uuid) returns boolean language sql stable security definer set search_path=public set row_security=off as $$ select public.can_manage_receivables(target) or exists(select 1 from public.condominium_memberships where condominium_id=target and user_id=auth.uid() and role='payment_reviewer') $$;
create function public.can_read_financial_unit(target uuid) returns boolean language sql stable security definer set search_path=public set row_security=off as $$ select public.can_read_receivables(u.condominium_id) or exists(select 1 from public.unit_owners a join public.people p on p.id=a.person_id where a.unit_id=target and p.auth_user_id=auth.uid()) or exists(select 1 from public.unit_occupancies a join public.people p on p.id=a.person_id where a.unit_id=target and p.auth_user_id=auth.uid()) from public.units u where u.id=target $$;
create function public.can_read_board_aggregates(target uuid) returns boolean language sql stable security definer set search_path=public set row_security=off as $$ select public.can_read_receivables(target) or public.is_organization_owner_for_condominium(target) or exists(select 1 from public.condominium_memberships where condominium_id=target and user_id=auth.uid() and role='board_member') $$;
revoke all on function public.can_manage_receivables(uuid),public.can_read_receivables(uuid),public.can_read_financial_unit(uuid),public.can_read_board_aggregates(uuid) from public;
grant execute on function public.can_manage_receivables(uuid),public.can_read_receivables(uuid),public.can_read_financial_unit(uuid),public.can_read_board_aggregates(uuid) to authenticated,service_role;

create function public.assert_ledger_integrity() returns trigger language plpgsql security definer set search_path=public as $$ declare original public.receivable_ledger_entries; begin
 if new.entry_type='reversal' and new.reversal_of_entry_id is null then raise exception 'reversal source required'; end if;
 if new.entry_type<>'reversal' and new.reversal_of_entry_id is not null then raise exception 'only reversal entries may reverse'; end if;
 if new.reversal_of_entry_id is not null then select * into original from public.receivable_ledger_entries where id=new.reversal_of_entry_id for update; if original.id is null or original.entry_type='reversal' or original.unit_id<>new.unit_id or original.condominium_id<>new.condominium_id or original.currency_code<>new.currency_code or original.amount<>new.amount or original.receivable_item_id is distinct from new.receivable_item_id or original.direction=new.direction then raise exception 'invalid reversal'; end if; end if; return new; end $$;
create trigger ledger_integrity before insert on public.receivable_ledger_entries for each row execute function public.assert_ledger_integrity();
create function public.prevent_ledger_mutation() returns trigger language plpgsql as $$ begin raise exception 'ledger entries are immutable'; end $$;
create trigger ledger_immutable before update or delete on public.receivable_ledger_entries for each row execute function public.prevent_ledger_mutation();
create function public.protect_posted_batch() returns trigger language plpgsql as $$ begin if old.status<>'draft' then raise exception 'posted batches are immutable'; end if; if tg_op='DELETE' then return old; end if; return new; end $$;
create trigger batch_immutable before update or delete on public.charge_batches for each row execute function public.protect_posted_batch();

alter table public.charge_concepts enable row level security; alter table public.charge_batches enable row level security; alter table public.receivable_items enable row level security; alter table public.receivable_ledger_entries enable row level security; alter table public.opening_balance_imports enable row level security;
create policy concepts_read on public.charge_concepts for select using(public.can_read_receivables(condominium_id)); create policy concepts_insert on public.charge_concepts for insert with check(public.can_manage_receivables(condominium_id)); create policy concepts_update on public.charge_concepts for update using(public.can_manage_receivables(condominium_id)) with check(public.can_manage_receivables(condominium_id));
create policy batches_read on public.charge_batches for select using(public.can_read_receivables(condominium_id));
create policy items_read on public.receivable_items for select using(public.can_read_financial_unit(unit_id));
create policy ledger_read on public.receivable_ledger_entries for select using(public.can_read_financial_unit(unit_id));
create policy imports_read on public.opening_balance_imports for select using(public.can_manage_receivables(condominium_id));
revoke insert,update,delete on public.charge_batches,public.receivable_items,public.receivable_ledger_entries,public.opening_balance_imports from authenticated;
grant select on public.charge_concepts,public.charge_batches,public.receivable_items,public.receivable_ledger_entries,public.opening_balance_imports to authenticated;
grant insert,update on public.charge_concepts to authenticated;

create function public.insert_receivable_item_and_entry(target uuid,target_unit uuid,target_concept uuid,target_batch uuid,new_item_type public.receivable_item_type,new_entry_type public.ledger_entry_type,new_direction public.ledger_direction,item_description text,item_amount numeric,item_currency text,item_issue date,item_due date default null) returns public.receivable_items language plpgsql security definer set search_path=public set row_security=off as $$ declare item public.receivable_items; begin
 if item_amount<=0 or item_amount<>round(item_amount,2) or item_currency !~ '^[A-Z]{3}$' then raise exception 'invalid monetary amount'; end if;
 insert into public.receivable_items(condominium_id,unit_id,concept_id,charge_batch_id,item_type,description,issue_date,due_date,currency_code,original_amount,created_by) values(target,target_unit,target_concept,target_batch,new_item_type,item_description,item_issue,item_due,item_currency,item_amount,auth.uid()) returning * into item;
 insert into public.receivable_ledger_entries(condominium_id,unit_id,receivable_item_id,entry_type,direction,amount,currency_code,effective_date,description,source_id,created_by) values(target,target_unit,item.id,new_entry_type,new_direction,item_amount,item_currency,item_issue,item_description,target_batch,auth.uid()); return item; end $$;
revoke all on function public.insert_receivable_item_and_entry(uuid,uuid,uuid,uuid,public.receivable_item_type,public.ledger_entry_type,public.ledger_direction,text,numeric,text,date,date) from public,authenticated;

create function public.create_receivable_item(target uuid,target_unit uuid,target_concept uuid,item_description text,item_amount numeric,item_currency text,item_issue date,item_due date default null) returns jsonb language plpgsql security definer set search_path=public set row_security=off as $$ declare item public.receivable_items; begin if auth.uid() is null or not public.can_manage_receivables(target) then raise exception 'permission denied'; end if; item:=public.insert_receivable_item_and_entry(target,target_unit,target_concept,null,'charge','charge','debit',item_description,item_amount,item_currency,item_issue,item_due); return jsonb_build_object('item',to_jsonb(item),'outstanding_amount',to_char(item_amount,'FM999999999999990.00')); end $$;

create function public.preview_charge_batch(target uuid,target_concept uuid,batch_currency text,issue_on date,due_on date,method public.charge_batch_distribution,rows jsonb,fixed_amount numeric default null) returns jsonb language plpgsql security definer set search_path=public set row_security=off as $$ declare total numeric; begin if auth.uid() is null or not public.can_manage_receivables(target) then raise exception 'permission denied'; end if; if batch_currency !~ '^[A-Z]{3}$' or due_on<issue_on or jsonb_array_length(rows)=0 or not exists(select 1 from public.charge_concepts where id=target_concept and condominium_id=target and is_active) or exists(select 1 from jsonb_array_elements(rows) r group by r->>'unit_id' having count(*)>1) or exists(select 1 from jsonb_array_elements(rows) r where not exists(select 1 from public.units u where u.id=(r->>'unit_id')::uuid and u.condominium_id=target)) then raise exception 'invalid batch preview'; end if; if method='fixed_per_unit' then if fixed_amount is null or fixed_amount<=0 or fixed_amount<>round(fixed_amount,2) then raise exception 'invalid fixed amount'; end if; total:=fixed_amount*jsonb_array_length(rows); else if exists(select 1 from jsonb_array_elements(rows) r where (r->>'amount') is null or (r->>'amount')::numeric<=0 or (r->>'amount')::numeric<>round((r->>'amount')::numeric,2)) then raise exception 'invalid custom amount'; end if; select sum((r->>'amount')::numeric) into total from jsonb_array_elements(rows) r; end if; return jsonb_build_object('count',jsonb_array_length(rows),'currencyCode',batch_currency,'total',to_char(total,'FM999999999999990.00'),'rows',rows); end $$;

create function public.post_charge_batch(target uuid,target_concept uuid,batch_name text,batch_currency text,issue_on date,due_on date,method public.charge_batch_distribution,rows jsonb,key text,fixed_amount numeric default null) returns jsonb language plpgsql security definer set search_path=public set row_security=off as $$ declare batch public.charge_batches; row_data jsonb; amount_value numeric; item public.receivable_items; preview jsonb; result jsonb; begin
 if auth.uid() is null or not public.can_manage_receivables(target) then raise exception 'permission denied'; end if; perform pg_advisory_xact_lock(hashtextextended(target::text||':'||key,0)); select * into batch from public.charge_batches where condominium_id=target and idempotency_key=key; if found then return batch.result; end if;
 preview:=public.preview_charge_batch(target,target_concept,batch_currency,issue_on,due_on,method,rows,fixed_amount);
 insert into public.charge_batches(condominium_id,concept_id,name,issue_date,due_date,currency_code,distribution_method,idempotency_key,created_by) values(target,target_concept,batch_name,issue_on,due_on,batch_currency,method,key,auth.uid()) returning * into batch;
 for row_data in select value from jsonb_array_elements(rows) loop amount_value:=case when method='fixed_per_unit' then fixed_amount else (row_data->>'amount')::numeric end; item:=public.insert_receivable_item_and_entry(target,(row_data->>'unit_id')::uuid,target_concept,batch.id,'charge','charge','debit',batch_name,amount_value,batch_currency,issue_on,due_on); end loop;
 result:=preview||jsonb_build_object('batch_id',batch.id,'status','posted'); update public.charge_batches set status='posted',posted_at=now(),posted_by=auth.uid(),result=result where id=batch.id; return result; end $$;

create function public.preview_opening_balances(target uuid,rows jsonb) returns jsonb language plpgsql security definer set search_path=public set row_security=off as $$ declare valid jsonb:='[]'; errors jsonb:='[]'; row_data jsonb; n int:=1; issue text; begin if auth.uid() is null or not public.can_manage_receivables(target) then raise exception 'permission denied'; end if; for row_data in select value from jsonb_array_elements(rows) loop n:=n+1; issue:=null; if not exists(select 1 from public.units where condominium_id=target and code=trim(row_data->>'unit_code')) then issue:='Unknown unit'; elsif row_data->>'balance_type' not in ('debit','credit') then issue:='Invalid balance type'; elsif upper(row_data->>'currency_code') !~ '^[A-Z]{3}$' then issue:='Invalid currency'; elsif coalesce(row_data->>'amount','') !~ '^(0|[1-9][0-9]{0,15})(\.[0-9]{1,2})?$' or (row_data->>'amount')::numeric<=0 then issue:='Invalid amount'; else begin perform (row_data->>'effective_date')::date; exception when others then issue:='Invalid date'; end; end if; if issue is null and (select count(*) from jsonb_array_elements(rows) x where trim(x->>'unit_code')=trim(row_data->>'unit_code') and x->>'balance_type'=row_data->>'balance_type' and upper(x->>'currency_code')=upper(row_data->>'currency_code'))>1 then issue:='Duplicate row'; end if; if issue is null then valid:=valid||jsonb_build_array(row_data||jsonb_build_object('currency_code',upper(row_data->>'currency_code'))); else errors:=errors||jsonb_build_array(jsonb_build_object('row',n,'error',issue)); end if; end loop; return jsonb_build_object('valid',valid,'errors',errors); end $$;

create function public.import_opening_balances(target uuid,rows jsonb,key text,import_filename text default null) returns jsonb language plpgsql security definer set search_path=public set row_security=off as $$ declare row_data jsonb; unit_row public.units; item public.receivable_items; result jsonb; existing jsonb; metadata jsonb; begin
 if auth.uid() is null or not public.can_manage_receivables(target) then raise exception 'permission denied'; end if; perform pg_advisory_xact_lock(hashtextextended(target::text||':'||key,0)); select result into existing from public.opening_balance_imports where condominium_id=target and idempotency_key=key; if found then return existing; end if; metadata:=public.preview_opening_balances(target,rows); if jsonb_array_length(metadata->'errors')>0 or jsonb_array_length(metadata->'valid')<>jsonb_array_length(rows) then raise exception 'invalid opening balances'; end if;
 for row_data in select value from jsonb_array_elements(rows) loop select * into unit_row from public.units where condominium_id=target and code=trim(row_data->>'unit_code'); if row_data->>'balance_type'='debit' then item:=public.insert_receivable_item_and_entry(target,unit_row.id,null,null,'opening_balance','opening_debit','debit',coalesce(nullif(row_data->>'description',''),'Opening balance'),(row_data->>'amount')::numeric,upper(row_data->>'currency_code'),(row_data->>'effective_date')::date,null); else insert into public.receivable_ledger_entries(condominium_id,unit_id,entry_type,direction,amount,currency_code,effective_date,description,created_by) values(target,unit_row.id,'opening_credit','credit',(row_data->>'amount')::numeric,upper(row_data->>'currency_code'),(row_data->>'effective_date')::date,coalesce(nullif(row_data->>'description',''),'Opening balance'),auth.uid()); end if; end loop;
 result:=jsonb_build_object('created',jsonb_array_length(rows)); insert into public.opening_balance_imports(condominium_id,idempotency_key,filename,currency_codes,effective_date_min,effective_date_max,result,created_by) select target,key,import_filename,array_agg(distinct upper(x->>'currency_code')),min((x->>'effective_date')::date),max((x->>'effective_date')::date),result,auth.uid() from jsonb_array_elements(rows) x; return result; end $$;

create function public.reverse_receivable_item(target uuid,target_item uuid,reason text) returns jsonb language plpgsql security definer set search_path=public set row_security=off as $$ declare item public.receivable_items; entry public.receivable_ledger_entries; begin if auth.uid() is null or not public.can_manage_receivables(target) or coalesce(trim(reason),'')='' then raise exception 'invalid reversal'; end if; select * into item from public.receivable_items where id=target_item and condominium_id=target for update; if item.id is null or item.lifecycle_status<>'active' then raise exception 'receivable unavailable'; end if; for entry in select e.* from public.receivable_ledger_entries e where e.receivable_item_id=item.id and e.entry_type<>'reversal' and not exists(select 1 from public.receivable_ledger_entries r where r.reversal_of_entry_id=e.id) for update loop insert into public.receivable_ledger_entries(condominium_id,unit_id,receivable_item_id,entry_type,direction,amount,currency_code,effective_date,description,reversal_of_entry_id,created_by) values(entry.condominium_id,entry.unit_id,entry.receivable_item_id,'reversal',case entry.direction when 'debit' then 'credit'::public.ledger_direction else 'debit'::public.ledger_direction end,entry.amount,entry.currency_code,current_date,trim(reason),entry.id,auth.uid()); end loop; update public.receivable_items set lifecycle_status='reversed',reversed_at=now(),reversed_by=auth.uid(),reversal_reason=trim(reason) where id=item.id; return jsonb_build_object('id',item.id,'status','reversed'); end $$;

create view public.receivable_balances with(security_invoker=true) as select i.id,i.condominium_id,i.unit_id,i.concept_id,i.charge_batch_id,i.description,i.reference,i.issue_date,i.due_date,i.created_at,i.currency_code,to_char(i.original_amount,'FM999999999999990.00') original_amount,to_char(coalesce(sum(e.amount) filter(where e.direction='debit'),0),'FM999999999999990.00') debit_total,to_char(coalesce(sum(e.amount) filter(where e.direction='credit'),0),'FM999999999999990.00') credit_total,to_char(coalesce(sum(case e.direction when 'debit' then e.amount else -e.amount end),0),'FM999999999999990.00') outstanding_amount,case when i.lifecycle_status='reversed' then 'reversed' when coalesce(sum(case e.direction when 'debit' then e.amount else -e.amount end),0)=0 then 'settled' when coalesce(sum(e.amount) filter(where e.direction='credit'),0)>0 then 'partially_settled' else 'open' end status from public.receivable_items i left join public.receivable_ledger_entries e on e.receivable_item_id=i.id group by i.id;
grant select on public.receivable_balances to authenticated;

create function public.get_unit_statement(target uuid,target_unit uuid) returns table(effective_date date,created_at timestamptz,description text,debit text,credit text,running_balance text,currency_code text,reference text,entry_type public.ledger_entry_type) language sql stable security definer set search_path=public set row_security=off as $$ select e.effective_date,e.created_at,e.description,case when e.direction='debit' then to_char(e.amount,'FM999999999999990.00') end,case when e.direction='credit' then to_char(e.amount,'FM999999999999990.00') end,to_char(sum(case e.direction when 'debit' then e.amount else -e.amount end) over(partition by e.currency_code order by e.effective_date,e.created_at,e.id),'FM999999999999990.00'),e.currency_code,i.reference,e.entry_type from public.receivable_ledger_entries e left join public.receivable_items i on i.id=e.receivable_item_id where e.condominium_id=target and e.unit_id=target_unit and public.can_read_financial_unit(target_unit) order by e.effective_date,e.created_at,e.id $$;
create function public.get_receivables_summary(target uuid) returns table(currency_code text,total_debits text,total_credits text,net_outstanding text,units_with_debit_balance bigint,units_with_credit_balance bigint,overdue_amount text,upcoming_amount text) language sql stable security definer set search_path=public set row_security=off as $$ with unit_totals as(select e.currency_code,e.unit_id,sum(case e.direction when 'debit' then e.amount else -e.amount end) balance from public.receivable_ledger_entries e where e.condominium_id=target group by e.currency_code,e.unit_id), totals as(select e.currency_code,sum(e.amount) filter(where e.direction='debit') debits,sum(e.amount) filter(where e.direction='credit') credits from public.receivable_ledger_entries e where e.condominium_id=target group by e.currency_code), due as(select currency_code,sum(outstanding_amount::numeric) filter(where due_date<current_date and status not in ('settled','reversed')) overdue,sum(outstanding_amount::numeric) filter(where (due_date is null or due_date>=current_date) and status not in ('settled','reversed')) upcoming from public.receivable_balances where condominium_id=target group by currency_code) select t.currency_code,to_char(coalesce(t.debits,0),'FM999999999999990.00'),to_char(coalesce(t.credits,0),'FM999999999999990.00'),to_char(coalesce(t.debits,0)-coalesce(t.credits,0),'FM999999999999990.00'),count(*) filter(where u.balance>0),count(*) filter(where u.balance<0),to_char(coalesce(d.overdue,0),'FM999999999999990.00'),to_char(coalesce(d.upcoming,0),'FM999999999999990.00') from totals t left join unit_totals u using(currency_code) left join due d using(currency_code) where public.can_read_board_aggregates(target) group by t.currency_code,t.debits,t.credits,d.overdue,d.upcoming $$;
create function public.get_receivables_aging(target uuid) returns table(currency_code text,current_amount text,days_1_30 text,days_31_60 text,days_61_90 text,over_90 text) language sql stable security definer set search_path=public set row_security=off as $$ select b.currency_code,to_char(coalesce(sum(b.outstanding_amount::numeric) filter(where b.due_date is null or b.due_date>=current_date),0),'FM999999999999990.00'),to_char(coalesce(sum(b.outstanding_amount::numeric) filter(where current_date-b.due_date between 1 and 30),0),'FM999999999999990.00'),to_char(coalesce(sum(b.outstanding_amount::numeric) filter(where current_date-b.due_date between 31 and 60),0),'FM999999999999990.00'),to_char(coalesce(sum(b.outstanding_amount::numeric) filter(where current_date-b.due_date between 61 and 90),0),'FM999999999999990.00'),to_char(coalesce(sum(b.outstanding_amount::numeric) filter(where current_date-b.due_date>90),0),'FM999999999999990.00') from public.receivable_balances b where b.condominium_id=target and b.status not in ('settled','reversed') and public.can_read_board_aggregates(target) group by b.currency_code $$;

revoke all on function public.create_receivable_item(uuid,uuid,uuid,text,numeric,text,date,date),public.preview_charge_batch(uuid,uuid,text,date,date,public.charge_batch_distribution,jsonb,numeric),public.post_charge_batch(uuid,uuid,text,text,date,date,public.charge_batch_distribution,jsonb,text,numeric),public.preview_opening_balances(uuid,jsonb),public.import_opening_balances(uuid,jsonb,text,text),public.reverse_receivable_item(uuid,uuid,text),public.get_unit_statement(uuid,uuid),public.get_receivables_summary(uuid),public.get_receivables_aging(uuid) from public;
grant execute on function public.create_receivable_item(uuid,uuid,uuid,text,numeric,text,date,date),public.preview_charge_batch(uuid,uuid,text,date,date,public.charge_batch_distribution,jsonb,numeric),public.post_charge_batch(uuid,uuid,text,text,date,date,public.charge_batch_distribution,jsonb,text,numeric),public.preview_opening_balances(uuid,jsonb),public.import_opening_balances(uuid,jsonb,text,text),public.reverse_receivable_item(uuid,uuid,text),public.get_unit_statement(uuid,uuid),public.get_receivables_summary(uuid),public.get_receivables_aging(uuid) to authenticated,service_role;
