create type public.charge_concept_category as enum ('regular_dues','extraordinary_dues','service','penalty','adjustment','opening_balance','other');
create type public.charge_batch_distribution as enum ('fixed_per_unit','custom_per_unit');
create type public.charge_batch_status as enum ('draft','posted','reversed');
create type public.receivable_item_type as enum ('charge','opening_balance','adjustment');
create type public.receivable_lifecycle_status as enum ('active','reversed');
create type public.ledger_entry_type as enum ('charge','opening_debit','opening_credit','adjustment_debit','adjustment_credit','reversal');
create type public.ledger_direction as enum ('debit','credit');

create table public.charge_concepts (id uuid primary key default gen_random_uuid(), condominium_id uuid not null references public.condominiums(id) on delete cascade, code text not null, name text not null, description text, category public.charge_concept_category not null, default_currency_code text check (default_currency_code ~ '^[A-Z]{3}$'), default_amount numeric(18,2) check (default_amount is null or default_amount > 0), is_active boolean not null default true, created_by uuid not null references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(condominium_id, code));
create table public.charge_batches (id uuid primary key default gen_random_uuid(), condominium_id uuid not null references public.condominiums(id), concept_id uuid not null references public.charge_concepts(id), name text not null, period text check (period is null or period ~ '^\d{4}-\d{2}$'), issue_date date not null, due_date date not null, currency_code text not null check (currency_code ~ '^[A-Z]{3}$'), distribution_method public.charge_batch_distribution not null, status public.charge_batch_status not null default 'draft', idempotency_key text not null, posted_at timestamptz, posted_by uuid references auth.users(id), created_by uuid not null references auth.users(id), created_at timestamptz not null default now(), unique(condominium_id,idempotency_key));
create table public.receivable_items (id uuid primary key default gen_random_uuid(), condominium_id uuid not null references public.condominiums(id), unit_id uuid not null references public.units(id), concept_id uuid references public.charge_concepts(id), charge_batch_id uuid references public.charge_batches(id), item_type public.receivable_item_type not null, description text not null, reference text, issue_date date not null, due_date date, currency_code text not null check (currency_code ~ '^[A-Z]{3}$'), original_amount numeric(18,2) not null check (original_amount > 0), lifecycle_status public.receivable_lifecycle_status not null default 'active', created_by uuid not null references auth.users(id), created_at timestamptz not null default now(), reversed_at timestamptz, reversed_by uuid references auth.users(id), reversal_reason text);
create table public.receivable_ledger_entries (id uuid primary key default gen_random_uuid(), condominium_id uuid not null references public.condominiums(id), unit_id uuid not null references public.units(id), receivable_item_id uuid references public.receivable_items(id), entry_type public.ledger_entry_type not null, direction public.ledger_direction not null, amount numeric(18,2) not null check(amount > 0), currency_code text not null check(currency_code ~ '^[A-Z]{3}$'), effective_date date not null, description text not null, reversal_of_entry_id uuid unique references public.receivable_ledger_entries(id), source_id uuid, created_by uuid not null references auth.users(id), created_at timestamptz not null default now());
create table public.opening_balance_imports (id uuid primary key default gen_random_uuid(), condominium_id uuid not null references public.condominiums(id), idempotency_key text not null, filename text, currency_code text not null check(currency_code ~ '^[A-Z]{3}$'), effective_date date not null, result jsonb not null, created_by uuid not null references auth.users(id), created_at timestamptz not null default now(), unique(condominium_id,idempotency_key));

create or replace function public.can_manage_receivables(target uuid) returns boolean language sql stable security definer set search_path=public set row_security=off as $$ select public.is_organization_owner_for_condominium(target) or exists(select 1 from public.condominium_memberships where condominium_id=target and user_id=auth.uid() and role in ('condominium_admin','accountant')) $$;
create or replace function public.can_read_receivables(target uuid) returns boolean language sql stable security definer set search_path=public set row_security=off as $$ select public.can_manage_receivables(target) or exists(select 1 from public.condominium_memberships where condominium_id=target and user_id=auth.uid() and role='payment_reviewer') $$;
revoke all on function public.can_manage_receivables(uuid), public.can_read_receivables(uuid) from public; grant execute on function public.can_manage_receivables(uuid), public.can_read_receivables(uuid) to authenticated, service_role;

create function public.assert_ledger_integrity() returns trigger language plpgsql security definer set search_path=public as $$ begin if new.receivable_item_id is not null and not exists(select 1 from public.receivable_items i where i.id=new.receivable_item_id and i.condominium_id=new.condominium_id and i.unit_id=new.unit_id and i.currency_code=new.currency_code) then raise exception 'ledger item tenant or currency mismatch'; end if; if new.reversal_of_entry_id is not null and not exists(select 1 from public.receivable_ledger_entries e where e.id=new.reversal_of_entry_id and e.unit_id=new.unit_id and e.receivable_item_id is not distinct from new.receivable_item_id and e.currency_code=new.currency_code and e.amount=new.amount and e.direction <> new.direction) then raise exception 'invalid reversal'; end if; return new; end $$;
create trigger ledger_integrity before insert on public.receivable_ledger_entries for each row execute function public.assert_ledger_integrity();
create function public.prevent_ledger_mutation() returns trigger language plpgsql as $$ begin raise exception 'ledger entries are immutable'; end $$;
create trigger ledger_immutable before update or delete on public.receivable_ledger_entries for each row execute function public.prevent_ledger_mutation();

alter table public.charge_concepts enable row level security; alter table public.charge_batches enable row level security; alter table public.receivable_items enable row level security; alter table public.receivable_ledger_entries enable row level security; alter table public.opening_balance_imports enable row level security;
create policy concepts_read on public.charge_concepts for select using(public.can_read_receivables(condominium_id)); create policy concepts_write on public.charge_concepts for all using(public.can_manage_receivables(condominium_id)) with check(public.can_manage_receivables(condominium_id));
create policy batch_read on public.charge_batches for select using(public.can_read_receivables(condominium_id)); create policy batch_write on public.charge_batches for all using(public.can_manage_receivables(condominium_id)) with check(public.can_manage_receivables(condominium_id));
create policy item_read on public.receivable_items for select using(public.can_read_receivables(condominium_id) or exists(select 1 from public.unit_owners o join public.people p on p.id=o.person_id where o.unit_id=unit_id and p.auth_user_id=auth.uid()) or exists(select 1 from public.unit_occupancies o join public.people p on p.id=o.person_id where o.unit_id=unit_id and p.auth_user_id=auth.uid()));
create policy ledger_read on public.receivable_ledger_entries for select using(public.can_read_receivables(condominium_id) or exists(select 1 from public.receivable_items i where i.id=receivable_item_id));
create policy imports_read on public.opening_balance_imports for select using(public.can_manage_receivables(condominium_id));

create or replace function public.create_receivable_item(target uuid, target_unit uuid, target_concept uuid, item_description text, item_amount numeric, item_currency text, item_issue date, item_due date default null) returns jsonb language plpgsql security definer set search_path=public set row_security=off as $$ declare i public.receivable_items; begin if auth.uid() is null or not public.can_manage_receivables(target) then raise exception 'permission denied'; end if; if item_amount<=0 or item_currency !~ '^[A-Z]{3}$' or not exists(select 1 from public.units where id=target_unit and condominium_id=target) or (target_concept is not null and not exists(select 1 from public.charge_concepts where id=target_concept and condominium_id=target)) then raise exception 'invalid receivable'; end if; insert into public.receivable_items(condominium_id,unit_id,concept_id,item_type,description,issue_date,due_date,currency_code,original_amount,created_by) values(target,target_unit,target_concept,'charge',item_description,item_issue,item_due,item_currency,item_amount,auth.uid()) returning * into i; insert into public.receivable_ledger_entries(condominium_id,unit_id,receivable_item_id,entry_type,direction,amount,currency_code,effective_date,description,created_by) values(target,target_unit,i.id,'charge','debit',item_amount,item_currency,item_issue,item_description,auth.uid()); return jsonb_build_object('item',to_jsonb(i),'outstanding_amount',item_amount); end $$;
create or replace function public.reverse_receivable_item(target uuid, target_item uuid, reason text) returns jsonb language plpgsql security definer set search_path=public set row_security=off as $$ declare i public.receivable_items; e public.receivable_ledger_entries; begin if auth.uid() is null or not public.can_manage_receivables(target) or coalesce(trim(reason),'')='' then raise exception 'invalid reversal'; end if; select * into i from public.receivable_items where id=target_item and condominium_id=target for update; if i.id is null or i.lifecycle_status<>'active' then raise exception 'receivable unavailable'; end if; for e in select * from public.receivable_ledger_entries where receivable_item_id=i.id and reversal_of_entry_id is null loop insert into public.receivable_ledger_entries(condominium_id,unit_id,receivable_item_id,entry_type,direction,amount,currency_code,effective_date,description,reversal_of_entry_id,created_by) values(e.condominium_id,e.unit_id,e.receivable_item_id,'reversal',case when e.direction='debit' then 'credit'::public.ledger_direction else 'debit'::public.ledger_direction end,e.amount,e.currency_code,current_date,reason,e.id,auth.uid()); end loop; update public.receivable_items set lifecycle_status='reversed',reversed_at=now(),reversed_by=auth.uid(),reversal_reason=reason where id=i.id; return jsonb_build_object('id',i.id,'status','reversed'); end $$;
revoke all on function public.create_receivable_item(uuid,uuid,uuid,text,numeric,text,date,date), public.reverse_receivable_item(uuid,uuid,text) from public; grant execute on function public.create_receivable_item(uuid,uuid,uuid,text,numeric,text,date,date), public.reverse_receivable_item(uuid,uuid,text) to authenticated,service_role;

create view public.receivable_balances with (security_invoker=true) as select i.id,i.condominium_id,i.unit_id,i.currency_code,i.original_amount,coalesce(sum(e.amount) filter(where e.direction='debit'),0) debit_total,coalesce(sum(e.amount) filter(where e.direction='credit'),0) credit_total,coalesce(sum(case when e.direction='debit' then e.amount else -e.amount end),0) outstanding_amount,case when i.lifecycle_status='reversed' then 'reversed' when coalesce(sum(case when e.direction='debit' then e.amount else -e.amount end),0)=0 then 'settled' when coalesce(sum(e.amount) filter(where e.direction='credit'),0)>0 then 'partially_settled' else 'open' end status from public.receivable_items i left join public.receivable_ledger_entries e on e.receivable_item_id=i.id group by i.id;

create or replace function public.post_charge_batch(target uuid, target_concept uuid, batch_name text, batch_currency text, issue_on date, due_on date, method public.charge_batch_distribution, rows jsonb, key text) returns jsonb language plpgsql security definer set search_path=public set row_security=off as $$ declare b public.charge_batches; r jsonb; u public.units; amount_value numeric; total numeric:=0; count_value int:=0; begin if auth.uid() is null or not public.can_manage_receivables(target) or jsonb_typeof(rows)<>'array' then raise exception 'invalid batch'; end if; select * into b from public.charge_batches where condominium_id=target and idempotency_key=key; if found then return jsonb_build_object('batch_id',b.id,'status',b.status,'idempotent',true); end if; if not exists(select 1 from public.charge_concepts where id=target_concept and condominium_id=target and is_active) then raise exception 'invalid concept'; end if; insert into public.charge_batches(condominium_id,concept_id,name,issue_date,due_date,currency_code,distribution_method,idempotency_key,created_by) values(target,target_concept,batch_name,issue_on,due_on,batch_currency,method,key,auth.uid()) returning * into b; for r in select value from jsonb_array_elements(rows) loop u:=null; select * into u from public.units where id=(r->>'unit_id')::uuid and condominium_id=target; amount_value:=(r->>'amount')::numeric; if u.id is null or amount_value<=0 then raise exception 'invalid batch row'; end if; perform public.create_receivable_item(target,u.id,target_concept,batch_name,amount_value,batch_currency,issue_on,due_on); total:=total+amount_value; count_value:=count_value+1; end loop; update public.charge_batches set status='posted',posted_at=now(),posted_by=auth.uid() where id=b.id; return jsonb_build_object('batch_id',b.id,'count',count_value,'currency_code',batch_currency,'total',total); end $$;
create or replace function public.import_opening_balances(target uuid, rows jsonb, key text, import_filename text default null) returns jsonb language plpgsql security definer set search_path=public set row_security=off as $$ declare r jsonb; u public.units; amount_value numeric; result jsonb:=jsonb_build_object('created',0); existing jsonb; begin if auth.uid() is null or not public.can_manage_receivables(target) or jsonb_typeof(rows)<>'array' then raise exception 'invalid import'; end if; select result into existing from public.opening_balance_imports where condominium_id=target and idempotency_key=key; if found then return existing; end if; for r in select value from jsonb_array_elements(rows) loop select * into u from public.units where condominium_id=target and code=trim(r->>'unit_code'); amount_value:=(r->>'amount')::numeric; if u.id is null or amount_value<=0 or upper(r->>'currency_code') !~ '^[A-Z]{3}$' or r->>'balance_type' not in ('debit','credit') then raise exception 'invalid opening balance'; end if; if r->>'balance_type'='debit' then perform public.create_receivable_item(target,u.id,null,coalesce(r->>'description','Opening balance'),amount_value,upper(r->>'currency_code'),(r->>'effective_date')::date,null); else insert into public.receivable_ledger_entries(condominium_id,unit_id,entry_type,direction,amount,currency_code,effective_date,description,created_by) values(target,u.id,'opening_credit','credit',amount_value,upper(r->>'currency_code'),(r->>'effective_date')::date,coalesce(r->>'description','Opening balance'),auth.uid()); end if; result:=jsonb_set(result,'{created}',to_jsonb((result->>'created')::int+1)); end loop; insert into public.opening_balance_imports(condominium_id,idempotency_key,filename,currency_code,effective_date,result,created_by) values(target,key,import_filename,'USD',current_date,result,auth.uid()); return result; end $$;
revoke all on function public.post_charge_batch(uuid,uuid,text,text,date,date,public.charge_batch_distribution,jsonb,text), public.import_opening_balances(uuid,jsonb,text,text) from public; grant execute on function public.post_charge_batch(uuid,uuid,text,text,date,date,public.charge_batch_distribution,jsonb,text), public.import_opening_balances(uuid,jsonb,text,text) to authenticated,service_role;
